const d=window.APP_DATA, app=document.getElementById('app'), nav=[...document.querySelectorAll('.nav-item')];
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const ext=(url,label,cls='')=>`<a class="${cls}" href="${url}" target="_blank" rel="noopener noreferrer">${label}</a>`;
const qld=(date,time='00:00')=>new Date(`${date}T${time}:00+10:00`);
const ended=g=>new Date(qld(g.date,g.time).getTime()+90*60000)<new Date();
const hasResult=g=>Number.isFinite(g.homeScore)&&Number.isFinite(g.awayScore);
function countdown(){const now=new Date(),s=new Date(d.meta.nationalsStart),e=new Date(d.meta.nationalsEnd);if(now<s){const days=Math.ceil((s-now)/86400000);return {main:`${days}`,label:`day${days===1?'':'s'} to Nationals`,status:'Counting down'}}if(now<=e)return{main:'LIVE',label:'Nationals are underway',status:'Game on'};return{main:'✓',label:'Nationals complete',status:'Complete'}}
function nextGame(){return d.schedule.map(g=>({...g,when:qld(g.date,g.time)})).sort((a,b)=>a.when-b.when).find(g=>!ended(g))||d.finals.filter(f=>f.confirmed).map(g=>({...g,when:qld(g.date,g.time)})).sort((a,b)=>a.when-b.when).find(g=>!ended(g))||null}
function record(){let w=0,l=0,dr=0,gf=0,ga=0;d.schedule.filter(hasResult).forEach(g=>{const sa=g.home==='SA'?g.homeScore:g.awayScore,op=g.home==='SA'?g.awayScore:g.homeScore;gf+=sa;ga+=op;if(sa>op)w++;else if(sa<op)l++;else dr++});return{w,l,dr,gf,ga,played:w+l+dr}}
function title(t,a=''){return `<div class="section-title"><h2>${esc(t)}</h2>${a?`<small>${esc(a)}</small>`:''}</div>`}
function svgIcon(name){const paths={schedule:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18M8 14h.01M12 14h.01M16 14h.01M8 18h.01M12 18h.01"/>',nationals:'<path d="M12 22s7-4.5 7-12a7 7 0 1 0-14 0c0 7.5 7 12 7 12Z"/><circle cx="12" cy="10" r="2.5"/>',facebook:'<path d="M14 8h3V4.5c-.6-.1-1.8-.3-3.5-.3-3.5 0-5.9 2.1-5.9 6v3.3H4v4h3.6V24h4.4v-6.5h3.6l.6-4H12v-2.9c0-1.2.3-2.1 2-2.1Z"/>',messenger:'<path d="M21 11.5a8.4 8.4 0 0 1-9 8.5 9.5 9.5 0 0 1-2.8-.4L5 22l1.2-4A8.1 8.1 0 0 1 3 11.5 8.4 8.4 0 0 1 12 3a8.4 8.4 0 0 1 9 8.5Z"/><path d="m7.5 13.5 3-3 2.2 1.7 3.8-3.7-3 5-2.2-1.7-3.8 1.7Z"/>',hockey:'<path d="M6 3v10.5a4.5 4.5 0 0 0 4.5 4.5H14"/><path d="M14 18h6"/><ellipse cx="19" cy="21" rx="3" ry="1.3"/>',youtube:'<rect x="3" y="6" width="18" height="12" rx="4"/><path d="m10 9 5 3-5 3Z"/>',share:'<path d="M12 3v12M7 8l5-5 5 5"/><path d="M5 13v7h14v-7"/>'};return `<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${paths[name]||''}</svg>`}
function quick(label,sub,icon,kind,action){if(kind==='go')return `<button class="quick quick-${icon}" data-go="${action}"><span class="quick-icon">${svgIcon(icon)}</span><span class="quick-copy"><b>${label}</b><small>${sub}</small></span></button>`;return `<a class="quick quick-${icon}" href="${action}" target="_blank" rel="noopener noreferrer"><span class="quick-icon">${svgIcon(icon)}</span><span class="quick-copy"><b>${label}</b><small>${sub}</small></span></a>`}
function nextCard(g){if(!g)return `<div class="card"><b>No upcoming game locked in yet.</b><div class="notice">Finals depend on round-robin standings.</div></div>`;const match=g.home&&g.away?`${g.home} vs ${g.away}`:g.match;return `<div class="card next-game"><div class="kicker">NEXT GAME</div><div class="game-line"><div><h3>${esc(match)}</h3><small>${esc(g.dateLabel)} · Game ${esc(g.id)}</small></div><div class="game-time"><strong>${esc(g.timeLabel)}</strong><span>Queensland time</span></div></div><div class="meta-pills"><span class="pill gold">Arrive ${esc(g.arrivalLabel)}</span><span class="pill">${esc(g.venue||d.meta.venue)}</span></div></div>`}
function countdownCard(){const c=countdown();return `<div class="countdown-card home-countdown"><div><span class="countdown-number">${esc(c.main)}</span><div><strong>${esc(c.label)}</strong><small>27 Sep – 4 Oct 2026 · Skate Paradise, Queensland</small></div></div><span class="status-chip">${esc(c.status)}</span></div>`}
function announcements(){const items=(d.announcements||[]).filter(a=>a.active);if(!items.length)return'';return `${title('Team Announcements')}<div class="announcement-list">${items.map((a,i)=>`<article class="card announcement priority-${esc(a.priority||'info')}"><div class="announcement-top"><span class="announcement-badge">${a.priority==='important'?'IMPORTANT':a.priority==='reminder'?'REMINDER':'INFO'}</span><span>${esc(a.updated)}</span></div><h3>${esc(a.title)}</h3>${(a.sections||[]).length?`<div class="announcement-sections">${a.sections.map(s=>`<section class="announcement-section"><h4><span class="announcement-section-icon">${esc(s.icon||'')}</span>${esc(s.heading)}</h4><p>${esc(s.text)}</p></section>`).join('')}</div>`:`<p>${esc(a.message||'')}</p>`}<div class="announcement-meta">Posted by ${esc(a.author||'Team Manager')}</div>${(a.actions||[]).length?`<div class="announcement-actions">${a.actions.map(x=>ext(x.url,esc(x.label),'button-link')).join('')}</div>`:''}<button class="share-announcement" data-announcement="${i}">${svgIcon('share')}<span>Share to U9 Messenger</span></button></article>`).join('')}</div>`}
function home(){const g=nextGame();return `<img class="hero-img" src="./assets/sa-u9-home-hero.png" alt="SA U9 Nationals 2026">${countdownCard()}${nextCard(g)}${announcements()}${title('Quick Access')}<div class="quick-grid">${quick('Schedule & Results','Games, scores & finals','schedule','go','schedule')}${quick('Nationals','Event info & links','nationals','go','info')}${quick('Official Facebook','Nationals updates','facebook','url',d.meta.facebookCanonicalUrl)}${quick('U9 Messenger','Team group chat','messenger','url',d.meta.messengerGroupUrl)}${quick('HockeySyte','Results & stats','hockey','url',d.meta.hockeySyteUrl)}${quick('YouTube','Streams & videos','youtube','url',d.meta.youtubeUrl)}</div>${title('Official Nationals Feed')}<div class="card facebook-card"><div class="facebook-head"><div class="fb-logo">f</div><div><b>Australian Inline Hockey National Championships</b><small>Official Nationals Facebook page</small></div></div><iframe class="facebook-frame" loading="lazy" title="Official Nationals Facebook feed" src="https://www.facebook.com/plugins/page.php?href=${encodeURIComponent(d.meta.facebookCanonicalUrl)}&tabs=timeline&width=500&height=520&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=false"></iframe><div class="fallback"><span>If Facebook blocks the embedded feed, open the official page directly.</span>${ext(d.meta.facebookCanonicalUrl,'Open Facebook')}</div></div>${title('Need help?')}<div class="card help"><h3>Brooke (Team Manager) or Rohan (Coach)</h3><p>For U9 team questions, use our Messenger group so the right person can help quickly.</p><div class="help-actions">${ext(d.meta.messengerGroupUrl,'Open U9 Messenger Chat')}</div></div><div class="footer-note">Schedule ${d.meta.scheduleVersion} · Last updated ${d.meta.lastUpdated}</div>`}
function team(){return `${title('Official U9 Team Roster')}<div class="card official-roster-card"><img class="official-roster-img" src="./assets/sa-u9-official-roster.jpeg?v=15" alt="South Australia U9 Representative Team roster"></div>`}
function resultBlock(g){if(hasResult(g))return `<div class="result-final"><span>FINAL</span><strong>${esc(g.home)} ${g.homeScore} – ${g.awayScore} ${esc(g.away)}</strong></div>`;if(ended(g))return `<div class="notice result-pending">Game complete · official result pending. ${ext(d.meta.hockeySyteUrl,'Check HockeySyte')}</div>`;return ''}
function scheduleCard(g,cond=false){const match=g.home&&g.away?`${g.home} vs ${g.away}`:g.match;return `<div class="card schedule-card"><div class="top"><div class="date">${esc(g.dateLabel)}</div><div class="fixture">Game ${esc(g.id)}</div></div><h3>${esc(match)}</h3><div class="schedule-details"><div class="detail"><span>Game</span><strong>${esc(g.timeLabel)}</strong></div><div class="detail"><span>Team arrival</span><strong>${esc(g.arrivalLabel)}</strong></div></div>${resultBlock(g)}${cond?`<div class="notice">${esc(g.note)}</div>`:''}</div>`}
function schedule(){const upcoming=d.schedule.filter(g=>!ended(g)),past=d.schedule.filter(g=>ended(g)),r=record();return `<img class="header-img" src="./assets/schedule-results-header.png" alt="Schedule and Results"><div class="card"><div class="stats"><div><strong>${r.w}-${r.l}-${r.dr}</strong><span>W-L-D</span></div><div><strong>${r.gf}</strong><span>Goals For</span></div><div><strong>${r.ga}</strong><span>Goals Against</span></div></div><div class="official-results-link">${ext(d.meta.hockeySyteUrl,'View official HockeySyte results & stats')}</div></div>${title('Upcoming Games',d.meta.scheduleVersion)}${upcoming.length?upcoming.map(g=>scheduleCard(g)).join(''):`<div class="card">Round-robin games complete.</div>`}${past.length?`${title('Completed Games')}${past.map(g=>scheduleCard(g)).join('')}`:''}${title('Finals Pathway','Conditional · depends on ladder position')}<div class="card"><b>Finals are conditional</b><p>SA’s finals pathway depends on our position after the round robin. Please keep these times available. Confirmed SA matchups will be updated once known.</p></div>${d.finals.map(g=>scheduleCard(g,true)).join('')}<details class="training-details"><summary>Completed Nationals Training</summary>${d.training.map(t=>`<div class="training-row"><span>${esc(t.dateLabel)}</span><b>${esc(t.timeLabel)}</b></div>`).join('')}</details>`}
function rules(){return `<img class="header-img rules-header-img" src="./assets/rules-regs-header.png?v=15" alt="Rules and Regulations">
${title('What Kids Need to Wear')}<div class="card rule-lead"><h3>U9 player game equipment</h3><p>For games, every skater needs their official SA playing uniform plus the required protective equipment:</p><ul><li>Inline hockey skates</li><li>Inline hockey stick</li><li>Approved hockey helmet</li><li><b>Full-face cage / full-face protection</b> — mandatory for junior players</li><li>Approved hockey gloves</li><li>Elbow pads</li><li>Shin guards</li><li>Protective cup (male) or pelvic protective equipment (female)</li></ul><p class="rule-note">Helmets and face protection must be approved equipment. Protective equipment other than gloves, helmet/face protection and goalkeeper leg pads is worn under the uniform.</p></div>
<details class="rule-card" open><summary>SA uniform &amp; equipment rules</summary><div class="rule-body"><ul><li>Players must wear the <b>official SA playing uniform</b> for games and warm-ups.</li><li>Uniforms must be clean and in good repair. A referee can prevent a player from playing in an inappropriate uniform.</li><li><b>White stick tape only.</b> Black or coloured stick tape is not permitted.</li><li><b>Clear tape only</b> may be used on playing uniforms.</li><li>Stick blades must be in good condition and may be checked by officials.</li><li>Skates may also be randomly checked. Equipment that could damage the playing surface must be corrected before the player can play.</li></ul></div></details>
<details class="rule-card"><summary>Goalkeepers</summary><div class="rule-body"><p>Goalkeepers require their full regulation goalie setup, including inline goalie skates, goalie stick, leg pads, chest protector, regulation goalkeeper gloves, approved helmet/face mask and protective cup or pelvic protection. Any forearm guards must be soft, pliable and conform to the forearms.</p></div></details>
<details class="rule-card" open><summary>Before every game</summary><div class="rule-body"><ul><li>Players should be at the venue <b>at least 1 hour before</b> their scheduled game.</li><li>The team must be completely ready to take the playing surface <b>15 minutes before</b> game time.</li><li>Players must wait for the referees before entering the playing surface.</li><li>Warm-up is 2 minutes. Games are 2 × 20-minute periods with a 1-minute half-time and one 30-second timeout per team per half. Timings can be reduced if the tournament schedule is delayed.</li></ul></div></details>
<details class="rule-card"><summary>Skates, sticks, pucks &amp; bags</summary><div class="rule-body"><ul><li>Skates may only be worn on the playing surface and when travelling to/from the change room for an official game — <b>no skating around the venue</b>.</li><li>Sticks and pucks are for the playing surface only. No shooting, stickhandling or playing with pucks in corridors, change areas, car parks or outside the venue.</li><li>Sticks/pucks used outside the playing surface may be confiscated until the end of the Championships.</li><li>Hockey bags and gear must be kept in designated areas.</li></ul></div></details>
<details class="rule-card"><summary>Change areas &amp; parents</summary><div class="rule-body"><ul><li>Marshalling/change areas must be kept clear.</li><li>Only scheduled players, coaches, managers, designated bench officials and Championship officials are permitted in restricted competitor areas.</li><li>Families and spectators must remain outside those restricted areas.</li><li>After games, teams need to clear the change area promptly — within 20 minutes after the game or by half-time of the following game.</li></ul><p class="rule-note">For our U9s, follow any venue/team instructions Brooke provides about parent assistance with dressing.</p></div></details>
<details class="rule-card"><summary>Finals eligibility</summary><div class="rule-body"><p>Players must meet the Championship's <b>50% + 1 round-robin participation requirement</b> to be eligible for finals. A player who is not injured, suspended or awaiting medical clearance can count as having played when dressed in the correct playing equipment and on the bench.</p><p><b>If your child may miss a game, contact Brooke as early as possible.</b> The Championship Director makes the final eligibility determination.</p></div></details>
<details class="rule-card"><summary>Finals game format</summary><div class="rule-body"><ul><li>In finals, the last 2 minutes become stop time when the score is within one goal.</li><li>If tied: 2-minute rest, then 5-minute sudden-death overtime.</li><li>If still tied: 2-minute rest, then best-of-3 shootout.</li><li>If still tied after that, the shootout continues sudden-death.</li></ul></div></details>
<details class="rule-card"><summary>Presentations</summary><div class="rule-body"><ul><li>Medal/presentation teams must wear their <b>State uniform</b>.</li><li>Only players from the final game may remain in playing gear/skates for presentations.</li></ul></div></details>
<details class="rule-card"><summary>Injuries, first aid &amp; concussion</summary><div class="rule-body"><ul><li>A Sports Trainer will be present at the Championships.</li><li>If a player is injured on the rink, parents and team personnel must <b>not enter the playing surface unless directed by the referee</b>.</li><li>The referee decides whether first-aid assistance is required and may call the Team Manager or first-aid officer onto the rink.</li><li>Skate Australia uses Australian Sports Commission concussion guidelines.</li></ul></div></details>
<details class="rule-card"><summary>Photos &amp; video</summary><div class="rule-body"><ul><li>Parents/spectators may take photos and private video from spectator safety areas, subject to safeguarding and consent requirements.</li><li><b>No flash photography</b> during competition.</li><li>Do not enter restricted areas to take photos/video.</li></ul></div></details>
<details class="rule-card"><summary>Spectator behaviour</summary><div class="rule-body"><ul><li>The Skate Australia Code of Conduct applies throughout Nationals.</li><li>No abusive language, harassment, ridicule, discriminatory comments, threats, physical altercations or undue pressure on children.</li><li>Referee decisions are not to be argued with and inappropriate behaviour toward officials is not tolerated.</li><li>No BYO alcohol. Alcohol may only be purchased at the venue and consumed in designated areas.</li></ul></div></details>
${title('Official Rules')}<div class="card"><p class="rule-doc-intro">This page is the parent-friendly U9 summary. The official documents remain the authority if you need the full technical wording.</p><div class="rule-links">${ext(d.meta.championshipRulesUrl,'2026 Championship Regulations','button-link')}${ext(d.meta.inlineRulesUrl,'Inline Hockey Rules','button-link')}</div></div>`}
function linkCard(url,icon,name,desc){return ext(url,`<div class="link-icon">${icon}</div><div><b>${name}</b><small>${desc}</small></div><div class="chev">›</div>`,'card link-card')}
function info(){return `<img class="header-img" src="./assets/nationals-2026-header.png" alt="2026 National Championships">${title('Venue')}<div class="card"><b>${d.meta.venue}</b><p>${d.meta.address}</p>${ext(d.meta.mapsUrl,'Open in Maps','button-link')}</div>${title('Official Nationals')}${linkCard(d.meta.facebookCanonicalUrl,'f','Official Nationals Facebook','News and event updates')}${linkCard(d.meta.youtubeUrl,'▶','Nationals YouTube','Streams and game videos')}${linkCard(d.meta.hockeySyteUrl,'🏒','HockeySyte','Official game sheets, results and stats')}${title('Registrations & Integrity')}${linkCard(d.meta.revolutioniseUrl,'✓','Revolutionise Registration','Nationals registration')}${linkCard(d.meta.siaUrl,'SIA','Sport Integrity Australia','eLearning / Clean Sport 101')}${title('Documents')}${linkCard(d.meta.teamUploadsUrl,'↑','Upload Medical Forms & SIA Certificates','U9 team document upload folder')}${linkCard(d.meta.teamSpreadsheetUrl,'✓','U9 Team Information & Checklist','Track uploads and complete missing team details')}${linkCard(d.meta.championshipRulesUrl,'PDF','2026 Championship Rules','Official Skate Australia championship document')}${linkCard(d.meta.inlineRulesUrl,'🏒','Inline Hockey Rules','Official Skate Australia inline hockey rules resource')}${linkCard(d.meta.fullDrawUrl,'XLS','Full Nationals Draw v2.8','Updated 18 September 2026 · Download the complete draw')}${title('Team Contact')}<div class="card help"><h3>Brooke (Team Manager) or Rohan (Coach)</h3><p>Use the U9 Messenger group for team questions.</p><div class="help-actions">${ext(d.meta.messengerGroupUrl,'Open U9 Messenger Chat')}</div></div>`}

const pages={home,schedule,team,rules,info};
function wireAnnouncements(){document.querySelectorAll('.share-announcement').forEach(btn=>btn.addEventListener('click',async()=>{const a=(d.announcements||[]).filter(x=>x.active)[Number(btn.dataset.announcement)];if(!a)return;const actionText=(a.actions||[]).map(x=>`${x.label}: ${x.url}`).join('\n');const body=(a.sections||[]).length?a.sections.map(s=>`${s.icon||''} ${s.heading}\n${s.text}`).join('\n\n'):(a.message||'');const text=`${a.priority==='important'?'IMPORTANT: ':''}${a.title}\n\n${body}${actionText?`\n\n${actionText}`:''}\n\n— ${a.author||'Team Manager'}`;try{if(navigator.share){await navigator.share({title:a.title,text});return}await navigator.clipboard.writeText(text);window.open(d.meta.messengerGroupUrl,'_blank','noopener');btn.querySelector('span').textContent='Copied — paste in Messenger'}catch(e){try{await navigator.clipboard.writeText(text)}catch(_){}window.open(d.meta.messengerGroupUrl,'_blank','noopener')}}))}
function render(page='home'){app.innerHTML=pages[page]();nav.forEach(b=>b.classList.toggle('active',b.dataset.page===page));document.querySelectorAll('[data-go]').forEach(el=>el.onclick=()=>render(el.dataset.go));wireAnnouncements();window.scrollTo({top:0,behavior:'instant'})}
nav.forEach(b=>b.addEventListener('click',()=>render(b.dataset.page)));
render('home');
if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js?v=15').catch(()=>{});}
