const d=window.APP_DATA, app=document.getElementById('app'), nav=[...document.querySelectorAll('.nav-item')];
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const qld=(date,time='00:00')=>new Date(`${date}T${time}:00+10:00`);
const ended=g=>new Date(qld(g.date,g.time).getTime()+90*60000)<new Date();
const hasResult=g=>Number.isFinite(g.homeScore)&&Number.isFinite(g.awayScore);
function countdown(){const now=new Date(),s=new Date(d.meta.nationalsStart),e=new Date(d.meta.nationalsEnd);if(now<s){const days=Math.ceil((s-now)/86400000);return `${days} day${days===1?'':'s'} to Nationals`}if(now<=e)return'Nationals are underway!';return'Nationals complete'}
function nextGame(){return d.schedule.map(g=>({...g,when:qld(g.date,g.time)})).sort((a,b)=>a.when-b.when).find(g=>!ended(g))||d.finals.filter(f=>f.confirmed).map(g=>({...g,when:qld(g.date,g.time)})).sort((a,b)=>a.when-b.when).find(g=>!ended(g))||null}
function record(){let w=0,l=0,dr=0,gf=0,ga=0;d.schedule.filter(hasResult).forEach(g=>{const sa=g.home==='SA'?g.homeScore:g.awayScore,op=g.home==='SA'?g.awayScore:g.homeScore;gf+=sa;ga+=op;if(sa>op)w++;else if(sa<op)l++;else dr++});return{w,l,dr,gf,ga}}
function title(t,a=''){return `<div class="section-title"><h2>${esc(t)}</h2>${a?`<small>${esc(a)}</small>`:''}</div>`}
function nextCard(g){if(!g)return `<div class="card"><b>No upcoming game locked in yet.</b><div class="notice">Finals depend on round-robin standings.</div></div>`;const match=g.home&&g.away?`${g.home} vs ${g.away}`:g.match;return `<div class="card next-game"><div class="kicker">NEXT GAME</div><div class="game-line"><div><h3>${esc(match)}</h3><small>${esc(g.dateLabel)} · Game ${esc(g.id)}</small></div><div class="game-time"><strong>${esc(g.timeLabel)}</strong><span>Queensland time</span></div></div><div class="meta-pills"><span class="pill gold">Arrive ${esc(g.arrivalLabel)}</span><span class="pill">${esc(g.venue||d.meta.venue)}</span></div></div>`}
function home(){const g=nextGame(),r=record();return `<img class="hero-img" src="./assets/sa-u9-home-hero.png" alt="SA U9 Nationals 2026"><div class="countdown"><div class="countdown-card"><strong>${esc(countdown())}</strong><small>27 September – 4 October 2026</small></div><div class="status-chip">SA U9</div></div>${nextCard(g)}${title('Quick Access')}<div class="quick-grid"><button class="quick" data-go="schedule"><span class="ico">▣</span><b>Schedule</b></button><button class="quick" data-go="team"><span class="ico">●●</span><b>Team</b></button><button class="quick" data-go="checklist"><span class="ico">✓</span><b>Checklist</b></button><a class="quick" href="${d.meta.messengerGroupUrl}" target="_blank"><span class="ico">💬</span><b>U9 Chat</b></a><a class="quick" href="${d.meta.hockeySyteUrl}" target="_blank"><span class="ico">🏒</span><b>Results</b></a><a class="quick" href="${d.meta.youtubeUrl}" target="_blank"><span class="ico">▶</span><b>YouTube</b></a></div>${title('Official Nationals Feed')}<div class="card facebook-card"><div class="facebook-head"><div class="fb-logo">f</div><div><b>Inline Hockey Australia</b><small>Official Nationals / ILHA updates</small></div></div><iframe class="facebook-frame" loading="lazy" title="Official Nationals Facebook feed" src="https://www.facebook.com/plugins/page.php?href=${encodeURIComponent(d.meta.facebookCanonicalUrl)}&tabs=timeline&width=500&height=520&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=false"></iframe><div class="fallback"><span>If Facebook blocks the embedded feed, use the official page directly.</span><a href="${d.meta.facebookShareUrl}" target="_blank">Open Facebook</a></div></div>${title('Results & Stats','ready for Nationals')}<div class="card"><div class="stats"><div><strong>${r.w}-${r.l}-${r.dr}</strong><span>W-L-D</span></div><div><strong>${r.gf}</strong><span>Goals For</span></div><div><strong>${r.ga}</strong><span>Goals Against</span></div></div><div class="sep"></div><div class="official-links"><a href="${d.meta.hockeySyteUrl}" target="_blank"><b>HockeySyte</b><small>Official results & stats</small></a><a href="${d.meta.youtubeUrl}" target="_blank"><b>YouTube</b><small>Streams & game video</small></a></div></div>${title('Need help?')}<div class="card help"><h3>Brooke (Team Manager) or Rohan (Coach)</h3><p>For U9 team questions, use our Messenger group so the right person can help quickly.</p><div class="help-actions"><a href="${d.meta.messengerGroupUrl}" target="_blank">Open U9 Messenger Chat</a></div></div><div class="footer-note">Schedule ${d.meta.scheduleVersion} · Last updated ${d.meta.lastUpdated}</div>`}
function team(){return `<img class="header-img" src="./assets/sa-u9-team-header.png" alt="SA U9 Team">${title('Players & Staff')} ${d.team.map(p=>`<div class="card person"><div class="avatar">${esc(p.badge||p.name[0])}</div><div class="person-copy"><strong>${esc(p.name)}</strong><small>${esc(p.role)}</small></div>${p.badge?`<div class="badge">${esc(p.badge)}</div>`:''}</div>`).join('')}${title('Team Staff')}${d.staff.map(p=>`<div class="card person"><div class="avatar staff">${esc(p.name[0])}</div><div class="person-copy"><strong>${esc(p.name)}</strong><small>${esc(p.role)}</small></div></div>`).join('')}`}
function scheduleCard(g,cond=false){const match=g.home&&g.away?`${g.home} vs ${g.away}`:g.match;const result=hasResult(g)?`<div class="notice">Final: ${g.home} ${g.homeScore} – ${g.awayScore} ${g.away}</div>`:'';return `<div class="card schedule-card"><div class="top"><div class="date">${esc(g.dateLabel)}</div><div class="fixture">Game ${esc(g.id)}</div></div><h3>${esc(match)}</h3><div class="schedule-details"><div class="detail"><span>Game</span><strong>${esc(g.timeLabel)}</strong></div><div class="detail"><span>Team arrival</span><strong>${esc(g.arrivalLabel)}</strong></div></div>${result}${cond?`<div class="notice">${esc(g.note)}</div>`:''}</div>`}
function schedule(){const upcoming=d.schedule.filter(g=>!ended(g)),past=d.schedule.filter(g=>ended(g));return `${title('Schedule',d.meta.scheduleVersion)}${upcoming.length?upcoming.map(g=>scheduleCard(g)).join(''):`<div class="card">Round-robin games complete.</div>`}${past.length?`${title('Past Games')}${past.map(g=>scheduleCard(g)).join('')}`:''}${title('Finals Pathway')} ${d.finals.map(g=>scheduleCard(g,true)).join('')}<details class="training-details"><summary>Completed Nationals Training</summary>${d.training.map(t=>`<div class="training-row"><span>${esc(t.dateLabel)}</span><b>${esc(t.timeLabel)}</b></div>`).join('')}</details>`}
function checklist(){return `${title('Nationals Checklist')} ${d.checklist.map((c,i)=>`<div class="card check"><div class="checkmark">${i+1}</div><div><h3>${esc(c.title)}</h3><p>${esc(c.detail)}</p></div></div>`).join('')}`}
function info(){return `<img class="header-img" src="./assets/nationals-2026-header.png" alt="2026 National Championships">${title('Venue')}<div class="card"><b>${d.meta.venue}</b><p>${d.meta.address}</p><a class="button-link" href="${d.meta.mapsUrl}" target="_blank">Open in Maps</a></div>${title('Official Links')}<a class="card link-card" href="${d.meta.facebookShareUrl}" target="_blank"><div class="link-icon">f</div><div><b>Official Nationals Facebook</b><small>News and event updates</small></div><div class="chev">›</div></a><a class="card link-card" href="${d.meta.youtubeUrl}" target="_blank"><div class="link-icon">▶</div><div><b>Nationals YouTube</b><small>Streams and game videos</small></div><div class="chev">›</div></a><a class="card link-card" href="${d.meta.hockeySyteUrl}" target="_blank"><div class="link-icon">🏒</div><div><b>HockeySyte</b><small>Official game sheets, results and stats</small></div><div class="chev">›</div></a><a class="card link-card" href="${d.meta.revolutioniseUrl}" target="_blank"><div class="link-icon">✓</div><div><b>Revolutionise Registration</b><small>Nationals registration</small></div><div class="chev">›</div></a><a class="card link-card" href="${d.meta.siaUrl}" target="_blank"><div class="link-icon">SIA</div><div><b>Sport Integrity Australia</b><small>eLearning / Clean Sport 101</small></div><div class="chev">›</div></a>${title('Need help?')}<div class="card help"><h3>Brooke (Team Manager) or Rohan (Coach)</h3><p>Use the U9 Messenger group for team questions.</p><div class="help-actions"><a href="${d.meta.messengerGroupUrl}" target="_blank">Open U9 Messenger Chat</a></div></div>${title('Quick Nationals Rules')}<ul class="card rules"><li>Game times shown are Queensland time (AEST).</li><li>Players should be at the venue at least one hour before each scheduled game.</li><li>Teams must be ready 15 minutes before game time.</li><li>Only white tape is permitted on stick blades.</li><li>Finals depend on round-robin standings.</li></ul>`}
const pages={home,schedule,team,checklist,info};
function render(page='home'){app.innerHTML=pages[page]();nav.forEach(b=>b.classList.toggle('active',b.dataset.page===page));document.querySelectorAll('[data-go]').forEach(el=>el.onclick=()=>render(el.dataset.go));window.scrollTo({top:0,behavior:'instant'})}
nav.forEach(b=>b.addEventListener('click',()=>render(b.dataset.page)));
render('home');
if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js?v=5').catch(()=>{});}
