const d=window.APP_DATA, app=document.getElementById('app'), nav=[...document.querySelectorAll('.nav-item')];
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const ext=(url,label,cls='')=>`<a class="${cls}" href="${url}" target="_blank" rel="noopener noreferrer">${label}</a>`;
const qld=(date,time='00:00')=>new Date(`${date}T${time}:00+10:00`);
const ended=g=>new Date(qld(g.date,g.time).getTime()+90*60000)<new Date();
const hasResult=g=>Number.isFinite(g.homeScore)&&Number.isFinite(g.awayScore);
function countdown(){const now=new Date(),s=new Date(d.meta.nationalsStart),e=new Date(d.meta.nationalsEnd);if(now<s){const days=Math.ceil((s-now)/86400000);return `${days} day${days===1?'':'s'} to Nationals`}if(now<=e)return'Nationals are underway!';return'Nationals complete'}
function nextGame(){return d.schedule.map(g=>({...g,when:qld(g.date,g.time)})).sort((a,b)=>a.when-b.when).find(g=>!ended(g))||d.finals.filter(f=>f.confirmed).map(g=>({...g,when:qld(g.date,g.time)})).sort((a,b)=>a.when-b.when).find(g=>!ended(g))||null}
function record(){let w=0,l=0,dr=0,gf=0,ga=0;d.schedule.filter(hasResult).forEach(g=>{const sa=g.home==='SA'?g.homeScore:g.awayScore,op=g.home==='SA'?g.awayScore:g.homeScore;gf+=sa;ga+=op;if(sa>op)w++;else if(sa<op)l++;else dr++});return{w,l,dr,gf,ga,played:w+l+dr}}
function title(t,a=''){return `<div class="section-title"><h2>${esc(t)}</h2>${a?`<small>${esc(a)}</small>`:''}</div>`}
function nextCard(g){if(!g)return `<div class="card"><b>No upcoming game locked in yet.</b><div class="notice">Finals depend on round-robin standings.</div></div>`;const match=g.home&&g.away?`${g.home} vs ${g.away}`:g.match;return `<div class="card next-game"><div class="kicker">NEXT GAME</div><div class="game-line"><div><h3>${esc(match)}</h3><small>${esc(g.dateLabel)} · Game ${esc(g.id)}</small></div><div class="game-time"><strong>${esc(g.timeLabel)}</strong><span>Queensland time</span></div></div><div class="meta-pills"><span class="pill gold">Arrive ${esc(g.arrivalLabel)}</span><span class="pill">${esc(g.venue||d.meta.venue)}</span></div></div>`}
function home(){const g=nextGame();return `<img class="hero-img" src="./assets/sa-u9-home-hero.png" alt="SA U9 Nationals 2026">${nextCard(g)}${title('Quick Access')}<div class="quick-grid"><button class="quick" data-go="schedule"><span class="ico">▣</span><b>Schedule & Results</b></button><button class="quick" data-go="info"><span class="ico">i</span><b>Nationals Info</b></button>${ext(d.meta.facebookCanonicalUrl,'<span class="ico">f</span><b>Official Facebook</b>','quick')}${ext(d.meta.messengerGroupUrl,'<span class="ico">💬</span><b>U9 Messenger</b>','quick')}${ext(d.meta.hockeySyteUrl,'<span class="ico">🏒</span><b>HockeySyte</b>','quick')}${ext(d.meta.youtubeUrl,'<span class="ico">▶</span><b>YouTube</b>','quick')}</div>${title('Official Nationals Feed')}<div class="card facebook-card"><div class="facebook-head"><div class="fb-logo">f</div><div><b>Australian Inline Hockey National Championships</b><small>Official Nationals Facebook page</small></div></div><iframe class="facebook-frame" loading="lazy" title="Official Nationals Facebook feed" src="https://www.facebook.com/plugins/page.php?href=${encodeURIComponent(d.meta.facebookCanonicalUrl)}&tabs=timeline&width=500&height=520&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=false"></iframe><div class="fallback"><span>If Facebook blocks the embedded feed, open the official page directly.</span>${ext(d.meta.facebookCanonicalUrl,'Open Facebook')}</div></div>${title('Need help?')}<div class="card help"><h3>Brooke (Team Manager) or Rohan (Coach)</h3><p>For U9 team questions, use our Messenger group so the right person can help quickly.</p><div class="help-actions">${ext(d.meta.messengerGroupUrl,'Open U9 Messenger Chat')}</div></div><div class="footer-note">Schedule ${d.meta.scheduleVersion} · Last updated ${d.meta.lastUpdated}</div>`}
function team(){return `<img class="header-img" src="./assets/sa-u9-team-header.png" alt="SA U9 Team">${title('Players & Staff')}${d.team.map(p=>`<div class="card person"><div class="avatar">${esc(p.badge||p.name[0])}</div><div class="person-copy"><strong>${esc(p.name)}</strong><small>${esc(p.role)}</small></div>${p.badge?`<div class="badge">${esc(p.badge)}</div>`:''}</div>`).join('')}${title('Team Staff')}${d.staff.map(p=>`<div class="card person"><div class="avatar staff">${esc(p.name[0])}</div><div class="person-copy"><strong>${esc(p.name)}</strong><small>${esc(p.role)}</small></div></div>`).join('')}`}
function resultBlock(g){if(hasResult(g))return `<div class="result-final"><span>FINAL</span><strong>${esc(g.home)} ${g.homeScore} – ${g.awayScore} ${esc(g.away)}</strong></div>`;if(ended(g))return `<div class="notice result-pending">Game complete · official result pending. ${ext(d.meta.hockeySyteUrl,'Check HockeySyte')}</div>`;return ''}
function scheduleCard(g,cond=false){const match=g.home&&g.away?`${g.home} vs ${g.away}`:g.match;return `<div class="card schedule-card"><div class="top"><div class="date">${esc(g.dateLabel)}</div><div class="fixture">Game ${esc(g.id)}</div></div><h3>${esc(match)}</h3><div class="schedule-details"><div class="detail"><span>Game</span><strong>${esc(g.timeLabel)}</strong></div><div class="detail"><span>Team arrival</span><strong>${esc(g.arrivalLabel)}</strong></div></div>${resultBlock(g)}${cond?`<div class="notice">${esc(g.note)}</div>`:''}</div>`}
function schedule(){const upcoming=d.schedule.filter(g=>!ended(g)),past=d.schedule.filter(g=>ended(g)),r=record();return `<img class="header-img" src="./assets/schedule-results-header.png" alt="Schedule and Results"><div class="card"><div class="stats"><div><strong>${r.w}-${r.l}-${r.dr}</strong><span>W-L-D</span></div><div><strong>${r.gf}</strong><span>Goals For</span></div><div><strong>${r.ga}</strong><span>Goals Against</span></div></div><div class="official-results-link">${ext(d.meta.hockeySyteUrl,'View official HockeySyte results & stats')}</div></div>${title('Upcoming Games',d.meta.scheduleVersion)}${upcoming.length?upcoming.map(g=>scheduleCard(g)).join(''):`<div class="card">Round-robin games complete.</div>`}${past.length?`${title('Completed Games')}${past.map(g=>scheduleCard(g)).join('')}`:''}${title('Finals Pathway')}${d.finals.map(g=>scheduleCard(g,true)).join('')}<details class="training-details"><summary>Completed Nationals Training</summary>${d.training.map(t=>`<div class="training-row"><span>${esc(t.dateLabel)}</span><b>${esc(t.timeLabel)}</b></div>`).join('')}</details>`}
function checklist(){return `<img class="header-img" src="./assets/nationals-checklist-header.png" alt="Nationals Checklist">${title('Before You Go')}${d.checklist.map((c,i)=>`<div class="card check"><div class="checkmark">${i+1}</div><div><h3>${esc(c.title)}</h3><p>${esc(c.detail)}</p></div></div>`).join('')}`}
function linkCard(url,icon,name,desc){return ext(url,`<div class="link-icon">${icon}</div><div><b>${name}</b><small>${desc}</small></div><div class="chev">›</div>`,'card link-card')}
function info(){return `<img class="header-img" src="./assets/nationals-2026-header.png" alt="2026 National Championships">${title('Venue')}<div class="card"><b>${d.meta.venue}</b><p>${d.meta.address}</p>${ext(d.meta.mapsUrl,'Open in Maps','button-link')}</div>${title('Official Nationals')} ${linkCard(d.meta.facebookCanonicalUrl,'f','Official Nationals Facebook','News and event updates')}${linkCard(d.meta.youtubeUrl,'▶','Nationals YouTube','Streams and game videos')}${linkCard(d.meta.hockeySyteUrl,'🏒','HockeySyte','Official game sheets, results and stats')}${title('Registrations & Integrity')}${linkCard(d.meta.revolutioniseUrl,'✓','Revolutionise Registration','Nationals registration')}${linkCard(d.meta.siaUrl,'SIA','Sport Integrity Australia','eLearning / Clean Sport 101')}${title('Documents')}${linkCard(d.meta.championshipRulesUrl,'PDF','2026 Championship Rules','Official Skate Australia championship document')}${linkCard(d.meta.fullDrawUrl,'XLS','Full Nationals Draw v2.6','Download the complete draw')}${title('Team Contact')}<div class="card help"><h3>Brooke (Team Manager) or Rohan (Coach)</h3><p>Use the U9 Messenger group for team questions.</p><div class="help-actions">${ext(d.meta.messengerGroupUrl,'Open U9 Messenger Chat')}</div></div>${title('Quick Nationals Rules')}<ul class="card rules"><li>Game times shown are Queensland time (AEST).</li><li>Players should be at the venue at least one hour before each scheduled game.</li><li>Teams must be ready 15 minutes before game time.</li><li>Only white tape is permitted on stick blades.</li><li>Finals depend on round-robin standings.</li></ul>`}
const pages={home,schedule,team,checklist,info};
function render(page='home'){app.innerHTML=pages[page]();nav.forEach(b=>b.classList.toggle('active',b.dataset.page===page));document.querySelectorAll('[data-go]').forEach(el=>el.onclick=()=>render(el.dataset.go));window.scrollTo({top:0,behavior:'instant'})}
nav.forEach(b=>b.addEventListener('click',()=>render(b.dataset.page)));
render('home');
if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js?v=6').catch(()=>{});}
